### ISSUE TITLE
date coercion should handle invalid records

### ISSUE THREAD

**Issue by ejoranlienea** [edanalytics/earthmover#20]
Invalid date formats raise an error, but should perhaps return a null value instead. Likely due to `to_datetime` default of `raise`: https://docs.dask.org/en/stable/generated/dask.dataframe.to_datetime.html
https://github.com/edanalytics/earthmover/blob/b5d0d1ac4fdfb468d32a4242ba11b2e118513f5f/earthmover/operations/column.py#L609

**Comment by jayckaiser** [comment]
There is an optional argument `errors` in `pd.to_datetime()` for handling errors like these. The default is set to 'raise' an exception if a row cannot be parsed. Other options are to 'coerce' the invalid value to NaT (i.e., NaN for datetimes), or to 'ignore' the invalid value and pass it through. We can change the default to whichever choice is preferable, or we can let the user specify in the Earthmover config YAML on how they want to tackle the problem on a case-by-case basis.

Additionally, we may want to add a check on the compile step to make sure the user has input a valid from_format string, as we do with other user-provided parameters in the Earthmover config file.

As an aside, because `pd.to_datetime()` (and many other pandas/dask methods) has many optional arguments, and because we can't codify all of them as Earthmover arguments, we may want to provide a path for the user to input kwargs that can be passed directly to the function. These would supercede Earthmover arguments and would not undergo the same datatype validation as Earthmover arguments. Just food for thought for a possible new extension to Earthmover.

**Comment by jayckaiser** [comment]
This feature was added in Earthmover 0.3.0 using the `ignore_errors` field.
